title: Computer postings
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://lidiomar.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: lidiomar
  email: lidiomar.f@gmail.com

google_analytics: "UA-58263416-1"
